### ISSUE TITLE
Styling a <li> element

### ISSUE THREAD

**Issue by geoff-maddock** [ffmad/HTMLtoOpenXML#1]
When I convert a `<li>`, I get an unstyled list - no bullet or number.

Is there a way to style this?  Either by adding styles to the HTML, or updating the conversion code?

It appears to assign the style:

```
</w:t></w:r><w:p startliste><w:r><w:t>
```

Which is later converted:

```
$output = preg_replace("/(<w:p startliste>)/mi", "</w:p><w:p><w:pPr><w:pStyle w:val='BulletStyle'/></w:pPr>", $output);
```

It isn't clear what BulletStyle is defined as.

**Comment by geoff-maddock** [comment]
I found that making this update inside of HTMLtoOpenXML.php was effective in styling a bulletted list.

```
private function processStyle($input) {
        $output = preg_replace("/(<w:p>)/mi", "<w:p><w:pPr><w:pStyle w:val='OurStyle2'/></w:pPr>", $input);

        // numId = 3 is bulleted
        $output = preg_replace("/(<w:p startliste>)/mi", "</w:p><w:p><w:pPr><w:pStyle w:val='BulletStyle'/><w:numPr><w:ilvl w:val='0'/><w:numId w:val='3'/></w:numPr></w:pPr>", $output);
        return $output;
    }
```

**Comment by ffmad** [comment]
Hi ! It's been, literally, years since I've worked on that little plugin. Thanks for the update ^^

If it works for you, could you make a pull request ?

**Comment by rkorebrits** [comment]
I can confirm that the change works to create a list. 

I've created a pull request

**Comment by ffmad** [comment]
Thank you!
